# Generated by Django 3.2.25 on 2024-12-11 15:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('will_report_state', models.BooleanField(default=True)),
                ('state', jsonfield.fields.JSONField(default=dict)),
                ('traits', models.ManyToManyField(related_name='devices', to='smartDevices.Trait')),
            ],
        ),
    ]
