# Generated by Django 3.2.25 on 2024-12-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartDevices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='states_on',
            field=models.BooleanField(default=False),
        ),
    ]
